
spring:
  application:
    name: bendan-mail
  mail:
    default-encoding: UTF-8
    host: smtp.qq.com
    port: 587
    username: 1468258057@qq.com
    password: 1111111111






project:
  name: Bendan
  author: obeast
server:
  port: 9999
